CREATE DATABASE teste_cam;
use teste_cam;

CREATE TABLE users ( id INT NOT NULL AUTO_INCREMENT, name VARCHAR(50) NOT NULL, username VARCHAR(50) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id));

CREATE TABLE phonebook (id INT NOT NULL AUTO_INCREMENT, user_id INT NOT NULL, name VARCHAR(50) NOT NULL, phone VARCHAR(50) NOT NULL, mail VARCHAR(255) NOT NULL, PRIMARY KEY(id), FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE);

